# Generated by Django 2.1.2 on 2019-02-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20190221_0223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line4',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
    ]
