# Generated by Django 2.1.2 on 2019-02-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190221_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='line4',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='line4',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
